### ISSUE TITLE
3D Map - Example Wifidb 

### ISSUE THREAD

**Issue by Takieddinex** [acalcutt/WifiDB#1]
Hello, I'm trying to set up a 3D map. I've tested the latest version of MapLibre V2 but I'm having a problem with the WebGL not being able to load the tiles properly. However your example : https://github.com/maplibre/maplibre-gl-js/issues/1036#issuecomment-1055615766 , https://wifidb.net/demo/terrain_raster/test2.html#12.5/47.26475/11.40416  seems to be more adapted to my need if you can share the code please. 

Thank you

**Comment by acalcutt** [comment]
That example is a bit old and used an pre-pre release of maplibre with terrain that needed a slighly different syntax.

I have updated the syntax so it works with the latest version here ( https://stackblitz.com/edit/web-platform-nbnj7e?file=index.html )

**Comment by Takieddinex** [comment]
Thank you very much, however, I would know if I can change the style of the map and put it in a different style. my map for example : 

![image](https://user-images.githubusercontent.com/95845810/171416348-ccccfe8e-453b-4248-be0e-34f096ba0fb3.png)

**Comment by acalcutt** [comment]
you should be able to use any style I would think. Though if your style doesn't have hillshade, it may be hard to notice is working without also adding a hillshade layer.

In the example at https://stackblitz.com/edit/web-platform-nbnj7e?file=index.html , Just go down to line 28 and change this 
`    style: 'https://tiles.wifidb.net/styles/WDB_OSM/style.json', // style URL`

**Comment by Takieddinex** [comment]
It works, Thank you, you are great !!

**Comment by Takieddinex** [comment]
@acalcutt  do you have any idea why when we add the terrain to a simple map the models we imported disappear as you can see on the following two screenshots : 

![image](https://user-images.githubusercontent.com/95845810/171432014-2b5301fe-c332-4f34-bff3-06089e9656c2.png)

![image](https://user-images.githubusercontent.com/95845810/171432093-3485d6a0-3456-452b-b5f6-04f17bcc262f.png)

only with a simple click on the right button 

otherwise when I zoom out I get this  

![image](https://user-images.githubusercontent.com/95845810/171432558-d00d2c09-d3dc-49dc-8ca0-ed49421b84db.png)

**Comment by acalcutt** [comment]
My guess would be the 3d objects are not taking elevation into account, so the are stuck under the surface at elevation 0

I know early on in terrain3d development I had similar issues with points, where they where under the ground, but max was able to fix that quickly. Might be worth posting an issue on the maplibre github for that one

**Comment by Takieddinex** [comment]
Great, Thank you !!
